/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <string.h>
#include "find-day.h"


long long day_to_be_added( CLIENT *clnt, int day_of_month, int month,long long year) {
	date this_date;
	int *output;

	this_date.day = day_of_month;
	this_date.month = month;
	this_date.year_upper = year >> 32;
	this_date.year_lower = year & 0x00000000FFFFFFFF;
	output = days_to_be_added_1(&this_date,clnt);
	if (output==NULL) {
		fprintf(stderr,"Trouble calling remote procedure\n");

	}
	
	return *output; 
}

long long find_week_day( CLIENT *clnt, long long total_no_days) {
	date this_date;
	int *output;
	this_date.year_upper = total_no_days >> 32;
	this_date.year_lower = total_no_days & 0x00000000FFFFFFFF;
	this_date.day = total_no_days;
	output = find_day_1(&this_date,clnt);
	if (output==NULL) {
		fprintf(stderr,"Trouble calling remote procedure\n");

	}
	
	return *output; 
}

long long day_elapsed(CLIENT *clnt, int day_of_month, int month,long long year) {
	date this_date;
	int *output;

	this_date.day = day_of_month;
	this_date.month = month;
	this_date.year_upper = year >> 32;
	this_date.year_lower = year & 0x00000000FFFFFFFF;


	output = days_elapsed_1(&this_date,clnt);
	if (output==NULL) {
		fprintf(stderr,"Trouble calling remote procedure\n");

	}
	
	return *output; 
}

int findDay(CLIENT *clnt) {
	int day_of_month=9,month = 8;
	long long year = 2014;

	printf("\nEnter date\n");
	scanf("%d/%d/%lld",&day_of_month,&month,&year);

	long long no_of_days = day_elapsed(clnt,day_of_month,month,year);
	long long leap_years = day_to_be_added(clnt,day_of_month,month,year);

	int day = find_week_day(clnt,no_of_days+leap_years);
	

	if(day == 0)
		printf("Monday\n");
	else if(day == 1)
		printf("Tuesday\n");
	else if(day == 2)
		printf("Wednesday\n");
	else if(day == 3)
		printf("Thursday\n");
	else if(day == 4)
		printf("Friday\n");
	else if(day == 5)
		printf("Saturday\n");
	else
		printf("Sunday\n");
}

int findDifference(CLIENT *clnt) {
	printf("Enter Date Range\n");
	int m1,d1,y1,m2,d2,y2,specific_day;
	scanf("%d/%d/%d %d/%d/%d %d",&d1,&m1,&y1,&d2,&m2,&y2,&specific_day);
}
int main(int argc,char *argv[]) {
	CLIENT *clnt;
	

	if(argc != 4) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	clnt = clnt_create(argv[1],SIMP_PROG,SIMP_VERSION,"udp");

	if (clnt == (CLIENT *) NULL) { // create unsuccessful
		clnt_pcreateerror(argv[1]);
		exit(1);
	}
	findDay(clnt);
	return 0;
}