/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "find-day.h"

int * days_to_be_added_1_svc(date *argp,struct svc_req *rqstp)
{

	static int  result;

	result = 23;
	/*
	 * insert server code here
	 */

	return(&result);
}

int * days_elapsed_1_svc(date *argp,struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * find_day_1_svc(date *argp,struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
